app_for_bimamitra/urls.py
from django.urls import path
from . import views

app_name='bimamitra'
urlpatterns = [
    path('',views.home, name='home'),
    path('dashboard/', views.home, name='home'),
    path('about/', views.about, name='about'),
    path('contactus/',views.contactus, name='contactus'),
    path('bimamitra/', views.bimabot, name='bimabot'),
]

bimamitra/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include("app_for_bimamitra.urls"))
]

app_for_bimamitra/models.py
from django.db import models

# Create your models here.

# Class ContactUs creates a table for contact us page.

class ContactUs(models.Model):
    name = models.CharField(max_length=100)
    email = models.EmailField(max_length=100)
    subject = models.CharField(max_length=100, blank=True)
    message = models.TextField()

    def __str__(self):
        return self.name
    

class SearchRecord(models.Model):
    username = models.CharField(max_length=255, default='admin')
    user_input = models.CharField(max_length=1255)
    response = models.CharField(max_length=5000)
    date_time = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return f"{self.username} - {self.date_time}"

app_for_bimamitra/forms.py
# forms.py
from django import forms
from .models import ContactUs

'''
class InputForm(forms.Form):
    user_input = forms.CharField(
        label='Prompt your query here..', 
        max_length=1200, 
        widget=forms.Textarea(attrs={'class': 'large-input', 'row':15,'style': 'width: 90%; height: 50px;'})
    )
'''

class InputForm(forms.Form):
    user_input = forms.CharField(
        label='Prompt your query here..', 
        max_length=1200, 
        widget=forms.Textarea(attrs={'class': 'large-input autosize-textarea'})
    )
    


# this is form for contact us section which takes model 

class ContactUsForm(forms.ModelForm):
    class Meta:
        model = ContactUs
        fields = ['name', 'email', 'subject', 'message']

app_for_bimamitra/views.py
from django.shortcuts import render, HttpResponse
from .utils import *

# Create your views here.


def home(request):
    return render(request, "app_for_bimamitra/home.html")
    #return HttpResponse("this is homepage.")
def about(request):
    return render(request, "app_for_bimamitra/about.html")

# def contactus(request):
#     return render(request, "app_for_bimamitra/contactus.html")

def bimabot(request):

    return render(request, "app_for_bimamitra/bimabot.html")


from .forms import ContactUsForm
def contactus(request):
    if request.method == 'POST':
        form = ContactUsForm(request.POST)
        if form.is_valid():
            # form.save()  # This will save the form data to the ContactUs model
            # Redirect to a success page or return a response
            return render(request, "app_for_bimamitra/contactus.html")  
    else:
        form = ContactUsForm()

    return render(request, 'app_for_bimamitra/contactus.html', {'form': form})



from .forms import InputForm
from .models import SearchRecord
def bimabot(request):
    chat_history = []
    response_text = None
    user='admin'
    
    if request.method == "POST":
        form = InputForm(request.POST)
        print("***************"*20)
        print("Form data:", request.POST)
        if form.is_valid():
            print("form is valid")
            user_input = form.cleaned_data['user_input']     
            response_text = generate_response_rag(user_input)
            # SearchRecord.objects.create(
            #         username = user,
            #         user_input=user_input,
            #         response=response_text
            #         )

            form=InputForm()
        else:
            print("form is invalid")
    else:
        
        form=InputForm()


    
    chat_db = SearchRecord.objects.filter(username=user)
    for i in chat_db:
        conversation_dict = {
                "You": i.user_input,
                "BimaBot": i.response
            }
        chat_history.insert(0,conversation_dict)
        
    
    return render(request, "app_for_bimamitra/bimabot.html", {'form':form, 'response': response_text, 'chat_history':chat_history})

templates/app_for_bimamitra/about.html
{% extends "app_for_bimamitra/base.html" %}
{% load static %}

{% block secondary_title %} About {% endblock %}

{% block content %}
    <div class="first-container text-center" style="padding:40px;">
        <div class="container mt-5">
            <div class="shadow-lg p-3 mb-5 bg-body-tertiary rounded text-center">
            <h2 class="header">About BimaMitra</h2>
        </div>

        <div class="mb-4">
            <section id="our-story">
                <h3>Our Story</h3>
                <p>In the vibrant year of 2023, Bima Mitra was born—a startup with a zest for innovation and a pledge to demystify insurance. We've taken our first steps towards an audacious goal: to revolutionize the insurance sector. By infusing value into the workflows of insurers, agents, brokers, and the extensive network of industry players, Bima Mitra is on a journey to ascend as the torchbearer of insurance technology worldwide.</p>
            </section>
        </div>

        <div class="mb-4">
            <section id="our-ethos">
                <h3>Our Ethos</h3>
                <p>"Digital Insurance is Connected Insurance." This is our credo. We're not just participating in the market; we're on a mission to embed insurance into the very essence of business and impact daily life. Bima Mitra is committed to leading the charge in fostering a globally connected insurance experience.</p>
            </section>
        </div>

        <div class="mb-4">
            <section id="our-vanguard">
                <h3>Our Vanguard</h3>
                <p>At the helm of this avant-garde endeavor are our founders, Bhanudas Rawade and Ankit Baliyan—visionaries who envisage a world where insurance is no longer a maze but a clear path to peace of mind. They lead Bima Mitra with the promise of innovation, integrity, and an unwavering focus on the future. Join us as we embark on this transformative odyssey.</p>
            </section>
        </div>

        <div class="text-center">
            <p>Welcome to Bima Mitra: the nexus where simplicity and technology meet to create a seamless insurance journey for all.</p>
        </div>
    </div>
    </div>
{% endblock %}

templates/app_for_bimamitra/base.html
{% load static %}
<!DOCTYPE html>
<html>
    <head>
        <title>BimaMitra | {% block secondary_title %}{% endblock %}</title>

        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css">
        <!--<link rel="stylesheet" type="text/css" href="../../static/project_image/css/style.css">-->
        <link rel="stylesheet" type="text/css" href="{% static 'css/style.css' %}">
        <!-- 
        <link rel="stylesheet" type="text/css" href="{% static 'css/home.css' %}">
        <link rel="stylesheet" type="text/css" href="{% static 'css/bimabot.css' %}">
        <link rel="stylesheet" type="text/css" href="{% static 'css/contactus.css' %}">
        -->
        {% block head %}{% endblock head %} <!-- Head Block -->

    </head>
    <body>

    {% block navbar %} <!-- Navbar Block -->
        <nav class="navbar navbar-expand-lg navbar-dark bg-secondary">
            <a class="navbar-brand" href="../">
                <img src="{% static 'images/logo/icon.png' %}" alt="Logo" height="40">
                Bima Mitra</a>
            
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarNavDropdown">
                 
                <!-- To configure the content in navigation bar-->
                <ul class="navbar-nav ml-auto">
                    <li class="nav-item active">
                        <!-- Configure Home text -->
                        <a class="nav-link" href="{% url "bimamitra:home" %}">Home <span class="sr-only">(current)</span></a>
                    </li>

                    <li class="nav-item">
                        <!--Configure About text -->
                        <a class="nav-link" href="{% url "bimamitra:about" %}">About</a>
                    </li>            
                    
                    <!-- Adding dropdown for products page -->
                    <li class="nav-item dropdown">
                        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdownMenuLink" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                            Products
                        </a>
                        <div class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
                            <!-- Defining the content of the dropdown in Navigation bar -->
                            <a class="dropdown-item" href="{% url "bimamitra:bimabot" %}">Bima Mitra Prototype</a>
                            <a class="dropdown-item" href="#">Upcoming...</a>
                        </div>
                    </li>
                    
                    <!--Configure Contact us -->
                    <li class="nav-item">
                        <a class="nav-link" href="{% url "bimamitra:contactus" %}">Contact Us</a>
                    </li>
                    
                </ul>
                
            </div>
        </nav>
        {% endblock navbar %}
            
        {% block content %} <!-- Main Content Block -->
        
        {% endblock content %}

        {% block footer %} <!-- Footer Block -->
        <!-- Optional Footer Content Here -->
            <div class="text-center mt-5 fully-transparent-container">
                This website was developed by Ankit | All rights reserved @
            </div>
        {% endblock footer %}

        <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js"></script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js"></script>
        <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js"></script>

    </body>
</html>

templates/app_for_bimamitra/bimabot.html
{% extends "app_for_bimamitra/base.html" %}
{% load static %}

{% block secondary_title %} Application {% endblock %}

{% block content%}



<head>
    <!-- ... (head content) ... -->
</head>
    
    <body>
        <div class="first-container mt-4 text-center">
            <div class="container-fluid mt-5 text-center" >
                <div class="row-12">
                <div class="shadow-lg p-3 mb-5 bg-body-tertiary rounded p-3 mb-2 bg-light">
                    <div class="header"> Welcome to the BimaMitra WebApp.</h5>
                        
                </div>
            </div>

            <div class="centered-container centered-container-content" >
                <div class="center-box">
                    <div class="image-box">
                        <img src="{% static 'images/logo/title.jpeg' %}" alt="Image" class="box-image">
                    </div>
                </div>
                    
                <div class="form-container mt-5">
                    <form method="post" name="enq", id="chat-form">
                        {% csrf_token %}
                        <div class="row">
                            <div class="qform-group col-5 text-center">
                                <input required="required" placeholder="Enter your query here.." id="user_query" class="form-control" name="user_input" type="text">
                            </div>
                            <div class="col-lg-12 mt-4">
                                <button type="submit" title="Submit Your Message!" class="btn btn-success" id="submitButton" name="submit" value="Submit">Get Response</button>
                            </div>
                            <div class="qcol-lg-12 text-center">
                                <div id="alert-msg" class="alert-msg text-center"></div>
                            </div>
                        </div>
                    </form>		
                </div>

                <div class="disclaimer">
                    <p>
                        * This website is for informational purposes only. 
                    </p>
                </div>
                

                    
            </div>

            {% if response %}
                <div class="container-response">
                    <div id="response" class="response-container">
                        <p><strong>BimaMitra says:</strong> {{ response | safe }}</p>
                        
                    </div>
                </div>
            {% endif %}


            {% if chat_history %}
                <div class="container-history">
                    {% for message in chat_history %}
                    {% if 'BimaBot' in message %}
                    <div class="bot-message">
                        <p>
                            <img src="{% static 'images/logo/icon.png' %}" alt="Logo" width="30">
                            {{ message.BimaBot | safe }} 
                        </p>

                    </div>
                    {% endif %}
                    {% if 'You' in message %}
                    <div class="user-message">
                        <p><strong>You:</strong> {{ message.You }}</p>
                    </div>
                    {% endif %}
                    {% endfor %}
                </div>
            {% endif %}
        
        </div>
    </body>
    

{%endblock%}


<!-- creating chat history view ====== left right alternate message
                <div class="main-container border border-black" style="width: auto; padding: 15px;">
                    <h2>Chat History</h2>
                    {% for message in chat_history %}
                        <div class="container border border-white" style = " width: 80%; margin-bottom: 5px;">

                            {% if 'BimaBot' in message %}
                                <div class="container border border-white text-left bg-light p-1">
                                    <div class="d-inline-block border border-dark rounded p-1">
                                        <p><strong>BimaBot:</strong> {{ message.BimaBot }}</p>
                                        
                                    </div>
                                </div>
                            {% endif %}
                            
                            {% if 'You' in message %}
                                <div class="container border border-white text-left bg-light p-2">
                                    <p><strong>You:</strong> {{ message.You }}</p>
                                    
                                </div>
                            {% endif %}
                        </div>
                        </div>
                    {% endfor %}
                    
                    -->

                    <!-- message in just one below another -->
        {% if chat_history %}
        <div class="container-history">
            <h4></h4>
            {% for message in chat_history %}
                {% if 'BimaBot' in message %}
                    <div class="bot-container">
                        <div class="text-left bg-light p-1">
                            <div class="d-inline-block border border-dark rounded p-1">
                                <p><strong>BimaBot:</strong> {{ message.BimaBot }}</p>
                            </div>
                        </div>
                    </div>
                {% endif %}
        
                {% if 'You' in message %}
                    <div class="user-container">
                        <div class="text-left bg-light p-2">
                            <p><strong>You:</strong> {{ message.You }}</p>
                        </div>
                    </div>
                {% endif %}
            {% endfor %}
        </div>
        {% endif %}

templates/app_for_bimamitra/contactus.html
{% extends "app_for_bimamitra/base.html" %}
{% load static %}

{% block secondary_title %} Contact Us {% endblock %}

{% block content%}

    <div class="first-container mt-4 text-center">
        <div class="container mt-5">
            <div class="shadow-lg p-3 mb-5 bg-body-tertiary rounded text-center">
            <h2 class="header">Great to see you wish to contact us!</h2>
        </div>
        
    </div>

    <div class="main-container " style="padding:29px">
        <section id="contact">
            <div class="container ">
                <div class="col-12">
                    <div class="row justify-content-center" style="padding:30px">
                        <h5> Write Your Query Below</h5>
                    </div>

                    <div class="row justify-content-center">
                        <div class="col-md-6">
                            <div class="field_form form_style3 animation" data-animation="fadeInUp" data-animation-delay="0.02s">
                                <form method="post" name="enq">
                                    {% csrf_token %}
                                    <div class="row">
                                        <div class="form-group col-12">
                                            <input required="required" placeholder="Enter Name *" id="first-name" class="form-control" name="name" type="text">
                                        </div>
                                        <div class="form-group col-12">
                                            <input required="required" placeholder="Enter Email *" id="email" class="form-control" name="email" type="email">
                                        </div>
                                        <div class="form-group col-12">
                                            <input placeholder="Enter Subject" id="subject" class="form-control" name="subject" type="text">
                                        </div>
                                        <div class="form-group col-lg-12">
                                            <textarea required="required" placeholder="Message *" id="description" class="form-control" name="message" rows="5"></textarea>
                                        </div>
                                        <div class="col-lg-12">
                                            <button type="submit" title="Submit Your Message!" class="btn btn-success" id="submitButton" name="submit" value="Submit">Submit</button>
                                        </div>
                                        <div class="col-lg-12 text-center">
                                            <div id="alert-msg" class="alert-msg text-center"></div>
                                        </div>
                                    </div>
                                </form>		
                            </div>
                        </div>
                </div>
            </div>
        </section>

    </div>

    

{% endblock %}

    

templates/app_for_bimamitra/home.html
{% extends "app_for_bimamitra/base.html" %}
{% load static %}

{% block secondary_title %}Home{% endblock %}
{% block content%}
    <!--Initializing block content -->
    <div class="first-container text-center" >
        

        <body>
            <div class="image-container">
                <img src="{% static 'images/home/home_image.png' %}" alt="Your Image Description">
            </div>


            <div class="header"> 
                Bima Mitra: Navigating Insurance with Intelligence
            </div>

            <div class="shadow-lg p-3 mb-5 bg-body-tertiary rounded p-3 mb-2 bg-light mt-2" style="color: black; font-size: 18px;">
                Welcome to Bima Mitra, your digital ally in the complex world of insurance. <br>
                With our advanced AI-driven tools and in-depth analytics, we bring clarity and simplicity to insurance processes. <br>
                Whether you're an individual seeking insurance advice or a professional looking for underwriting assistance, <br>
                <strong>Bima Mitra </strong> is your go-to InsureTech solution.
            </div>

            <!-- Features: -->
            <div class="light-grey-container">
                <div class="container-section">
                    Features at a Glance:
                </div>
                <div class="feature-list">
                    <ul>
                        <li>Interactive Q&A with effortless navigation</li>
                        <li>Comprehensive Insurance Information Repository</li>
                        <li>Streamlined Underwriting Assistant</li>
                        <li>Simplified Claim Processing Assistance</li>
                        <li>In-depth Data Analytics Support</li>
                    </ul>
                </div>
            </div>


            <div class="branding-text">
                Engage with Bima Mitra, <br> where technology meets insurance expertise
            </div>



            <!-- Why Bima Mitra -->
            <div class="light-grey-container">
                <div class="container-section">
                    Why Bima Mitra ?
                </div>
                <div class="why-bima-mitra">
                    Bima Mitra is the catalyst for swift digitization in the insurance sector, offering intuitive, API-driven connectivity for insurers and clients. It's the nexus where InsureTech innovation meets practical application, enabling seamless integration and deployment of digital insurance services at remarkable speed. Choose Bima Mitra to empower, enhance, and expedite your insurance experience
                </div>
        </div>



            <div class="highlight-heading">
                Bima Mitra is a complete Platform As A Service (PAAS) across products, <br> APIs and data essential to drive business growth
            </div>



            <div class="end-of-page-message">
                A whole new way to think about insurance infrastructure
            </div>
            
        </body>
        
    </div>


{%endblock%}

<div class="shadow-lg p-3 mb-5 bg-body-tertiary rounded p-3 mb-2 bg-light">
    <div class="header"> Welcome to the homepage of this WebApp - with database. </h5>
</div>

<a href="{% url 'bimamitra:bimabot' %}">Link to the App</a>